

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - sql_password
    env_file: .env
    environment:
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD_FILE: /run/secrets/sql_password
    networks:
     - inception
    volumes: 
      - mariadb:/var/lib/mysql
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    volumes: 
     - wordpress:/var/www/html
    restart: always
    depends_on: 
      - wordpress
    ports:
      - "443:443"

  wordpress:
    image: wordpress
    container_name: wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    secrets:
      - w_sql_password
      - userPass
      - adminPass
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/w_sql_password
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      URL: ${URL}
      TITLE: ${TITLE} 
      EMAILADMINE: ${EMAILADMINE}
      ADMINUSER: ${ADMINUSER}
      ADMINPASSWORD_FILE: /run/secrets/adminPass
      ROLEADMIN: ${ROLEADMIN}
      USERS: ${USERS}
      EMAILUSER: ${EMAILUSER}
      PASSWORD_FILE: /run/secrets/userPass
      ROLE: ${ROLE}
    networks:
      - inception
    volumes: 
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis
    container_name: redis
    build: 
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception
    restart: always

  ftp:
    image: ftp
    container_name: ftp
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    secrets:
      - ftpPass
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    env_file: .env
    environment :
      FTP_USER: ${FTPUSER}
      FTP_PASS_FILE: /run/secrets/ftpPass
      PASV_MIN_PORT: 21000
      PASV_MAX_PORT: 21010
    volumes:
      - wordpress:/home/ftpuser
    restart: always
    networks:
      - inception

  adminer:
    image: adminer
    container_name: adminer
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb
    networks:
      - inception

  portainer:
    image: portainer
    container_name: portainer
    build:
      context: requirements/bonus/portainer
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
  
  website:
    image: website
    container_name: website
    build:
      context: requirements/bonus/website
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - inception

volumes:
  wordpress:
    driver : local
    driver_opts :
      type : none
      o : bind
      device : /home/hchadili/data/wordpress
  mariadb:
    driver : local
    driver_opts :
      type : none
      o : bind
      device : /home/hchadili/data/mariadb

  portainer_data:
    driver : local
    driver_opts :
      type : none
      o : bind
      device : /home/hchadili/data/portainer

networks:
  inception:
    driver: bridge
secrets:
  sql_password:
    file: secrets/sql_password.txt
  w_sql_password:
    file: secrets/w_sql_password.txt
  adminPass:
    file: secrets/adminPass.txt
  userPass:
    file: secrets/userPass.txt
  ftpPass:
    file: secrets/ftpPass.txt