version: '3.2'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - sql_password
      - sql_root_password
    env_file: .env
    networks:
     - inception
    environment:
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD_FILE: /run/secrets/sql_password
      SQL_ROOT_PASSWORD_FILE: /run/secrets/sql_root_password
    volumes: 
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose: 
      - "3306"

  nginx:
    container_name: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    volumes: 
     - wordpress:/var/www/html
    restart: on-failure
    depends_on: 
      - wordpress
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    secrets:
      - w_sql_password
      - userPass
      - adminPass
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/w_sql_password
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      URL: ${URL}
      TITLE: ${TITLE} 
      EMAILADMINE: ${EMAILADMINE}
      ADMINUSER: ${ADMINUSER}
      ADMINPASSWORD_FILE: /run/secrets/adminPass
      ROLEADMIN: ${ROLE}
      USERS: ${USERS}
      EMAILUSER: ${EMAILUSER}
      PASSWORD_FILE: /run/secrets/userPass
      ROLE: ${ROLE}
    networks:
      - inception
    volumes: 
      - wordpress:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb
    expose: 
      - "9000"

  redis:
    container_name: redis
    build: 
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "6379:6379"
    restart: unless-stopped

  ftp:
    container_name: ftp
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    # image: fauria/vsftpd
    secrets:
      - ftpPass
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    env_file: .env
    environment :
      FTP_USER: ${FTPUSER}
      FTP_PASS_FILE: /run/secrets/ftpPass
      PASV_MIN_PORT: 21000
      PASV_MAX_PORT: 21010
    volumes:
      - wordpress:/home/ftpuser
    restart: unless-stopped
    networks:
      - inception

  adminer:
    container_name: adminer
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb
    networks:
      - inception

  portainer:
    # image:  portainer/portainer-ce:2.34.0-alpine
    container_name: portainer
    build:
      context: requirements/bonus/portainer
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9090:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
  
  website:
    container_name: website
    build:
      context: requirements/bonus/website
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - inception

  

volumes:
  wordpress: {}
  mariadb: {}
  portainer_data: {}

networks:
  inception:
    driver: bridge
secrets:
  sql_password:
    file: secrets/sql_password.txt
  sql_root_password:
    file: secrets/sql_root_password.txt
  w_sql_password:
    file: secrets/w_sql_password.txt
  adminPass:
    file: secrets/adminPass.txt
  userPass:
    file: secrets/userPass.txt
  ftpPass:
    file: secrets/ftpPass.txt